version: "3.8"

volumes:
  redis-data:
  postgres-data:

services:
  redis:
    container_name: redis
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

    restart: always

  postgres:
    container_name: postgres

    image: postgres:latest

    ports:
      - "5432:5432"

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}

    volumes:
      - postgres-data:/var/lib/postgresql/

    restart: always

  api:
    container_name: nyam-api

    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8000:8000"

    restart: always

    depends_on:
      - redis
      - postgres

  dramatiq:
    container_name: dramatiq

    build:
      context: .
      dockerfile: dramatiq.Dockerfile

    restart: always

    depends_on:
      - redis