cdn:
  url_format: https://cdn.nyam.online/{key}
  key_format:
    avatar: "avatars/{nickname}-{hex}{ext}"
    page: "pages/{chapter_id}-{hex}{ext}"

bot:
  headers:
    X-Requester: https://manga.nyam.online/bot

content_providers:
  hikka:
    name: Hikka
    description: "Hikka.io content provider"
    classname: HikkaContentProvider
    args:
      endpoint: https://api.hikka.io/
