"""add slug index

Revision ID: 00f20e72f05f
Revises: 9b9e4ca98311
Create Date: 2024-11-07 12:31:08.602931

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "00f20e72f05f"
down_revision: Union[str, None] = "9b9e4ca98311"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_service_compositions_slug"), "service_compositions", ["slug"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_service_compositions_slug"), table_name="service_compositions")
    # ### end Alembic commands ###
