"""add team verification

Revision ID: ed087f0042c1
Revises: 688ae9269f09
Create Date: 2024-12-14 16:15:23.318985

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ed087f0042c1"
down_revision: Union[str, None] = "688ae9269f09"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("service_teams", sa.Column("verified", sa.Boolean(), nullable=False))
    op.create_index(op.f("ix_service_teams_verified"), "service_teams", ["verified"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_service_teams_verified"), table_name="service_teams")
    op.drop_column("service_teams", "verified")
    # ### end Alembic commands ###
