"""password nullable for oauth 

Revision ID: 7ac1ccf53394
Revises: d304cea32d54
Create Date: 2024-11-25 19:40:01.957376

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7ac1ccf53394"
down_revision: Union[str, None] = "d304cea32d54"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("service_users", "password_hash", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    # ### commands auto generated by Alembic - please adjust! ###
    # ### Rollback this change may cause errors
    # op.alter_column("service_users", "password_hash", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
    """
