"""Genres as table

Revision ID: 0a72ddc6e89f
Revises: aae356a1470e
Create Date: 2024-11-23 02:29:50.152870

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0a72ddc6e89f"
down_revision: Union[str, None] = "aae356a1470e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "service_genres",
        sa.Column("name_uk", sa.String(), nullable=False),
        sa.Column("name_en", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_service_genres_created_at"), "service_genres", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_service_genres_id"), "service_genres", ["id"], unique=False)
    op.create_index(op.f("ix_service_genres_slug"), "service_genres", ["slug"], unique=False)
    op.create_index(
        op.f("ix_service_genres_updated_at"), "service_genres", ["updated_at"], unique=False
    )
    op.create_table(
        "association_composition_genres",
        sa.Column("first_id", sa.BIGINT(), nullable=False),
        sa.Column("second_id", sa.BIGINT(), nullable=False),
        sa.ForeignKeyConstraint(["first_id"], ["service_genres.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["second_id"], ["service_compositions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("first_id", "second_id"),
    )
    op.drop_column("service_compositions", "genres")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_compositions",
        sa.Column(
            "genres",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            server_default="{}",
            nullable=False,
        ),
    )
    op.drop_table("association_composition_genres")
    op.drop_index(op.f("ix_service_genres_updated_at"), table_name="service_genres")
    op.drop_index(op.f("ix_service_genres_slug"), table_name="service_genres")
    op.drop_index(op.f("ix_service_genres_id"), table_name="service_genres")
    op.drop_index(op.f("ix_service_genres_created_at"), table_name="service_genres")
    op.drop_table("service_genres")
    # ### end Alembic commands ###
