"""Add cascade deletion of team join requests

Revision ID: a8479cfb7f50
Revises: 730fea4159bd
Create Date: 2024-12-25 07:31:38.277178

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a8479cfb7f50"
down_revision: Union[str, None] = "730fea4159bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "service_team_join_requests_team_id_fkey", "service_team_join_requests", type_="foreignkey"
    )
    op.drop_constraint(
        "service_team_join_requests_user_id_fkey", "service_team_join_requests", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "service_team_join_requests", "service_users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "service_team_join_requests", "service_teams", ["team_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "service_team_join_requests", type_="foreignkey")
    op.drop_constraint(None, "service_team_join_requests", type_="foreignkey")
    op.create_foreign_key(
        "service_team_join_requests_user_id_fkey",
        "service_team_join_requests",
        "service_users",
        ["user_id"],
        ["id"],
    )
    op.create_foreign_key(
        "service_team_join_requests_team_id_fkey",
        "service_team_join_requests",
        "service_teams",
        ["team_id"],
        ["id"],
    )
    # ### end Alembic commands ###
