"""Add team join requests

Revision ID: 532b67ccf93c
Revises: ed087f0042c1
Create Date: 2024-12-15 15:10:40.602315

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "532b67ccf93c"
down_revision: Union[str, None] = "ed087f0042c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "service_team_join_requests",
        sa.Column("team_id", sa.BIGINT(), nullable=True),
        sa.Column("user_id", sa.BIGINT(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["service_teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["service_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_service_team_join_requests_created_at"),
        "service_team_join_requests",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_service_team_join_requests_id"), "service_team_join_requests", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_service_team_join_requests_status"),
        "service_team_join_requests",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_service_team_join_requests_updated_at"),
        "service_team_join_requests",
        ["updated_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_service_team_join_requests_updated_at"), table_name="service_team_join_requests"
    )
    op.drop_index(
        op.f("ix_service_team_join_requests_status"), table_name="service_team_join_requests"
    )
    op.drop_index(op.f("ix_service_team_join_requests_id"), table_name="service_team_join_requests")
    op.drop_index(
        op.f("ix_service_team_join_requests_created_at"), table_name="service_team_join_requests"
    )
    op.drop_table("service_team_join_requests")
    # ### end Alembic commands ###
