"""Add teams, team members and link composition variants to teams

Revision ID: 3e0588bb3768
Revises: cb4b65b248c9
Create Date: 2024-12-11 12:02:31.127435

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3e0588bb3768"
down_revision: Union[str, None] = "cb4b65b248c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "service_teams",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("members", sa.Integer(), nullable=False),
        sa.Column("variants", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("rated_by", sa.Integer(), nullable=False),
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_service_teams_created_at"), "service_teams", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_service_teams_description"), "service_teams", ["description"], unique=False
    )
    op.create_index(op.f("ix_service_teams_id"), "service_teams", ["id"], unique=False)
    op.create_index(op.f("ix_service_teams_members"), "service_teams", ["members"], unique=False)
    op.create_index(op.f("ix_service_teams_name"), "service_teams", ["name"], unique=False)
    op.create_index(op.f("ix_service_teams_rated_by"), "service_teams", ["rated_by"], unique=False)
    op.create_index(op.f("ix_service_teams_rating"), "service_teams", ["rating"], unique=False)
    op.create_index(
        op.f("ix_service_teams_updated_at"), "service_teams", ["updated_at"], unique=False
    )
    op.create_index(op.f("ix_service_teams_variants"), "service_teams", ["variants"], unique=False)
    op.create_table(
        "service_team_members",
        sa.Column("pseudonym", sa.String(), nullable=True),
        sa.Column("user_id", sa.BIGINT(), nullable=True),
        sa.Column("team_id", sa.BIGINT(), nullable=True),
        sa.Column("role_id", sa.BIGINT(), nullable=True),
        sa.Column("variants", sa.Integer(), nullable=False),
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("local_permissions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["service_roles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["service_teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["service_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_service_team_members_created_at"),
        "service_team_members",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_service_team_members_id"), "service_team_members", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_service_team_members_updated_at"),
        "service_team_members",
        ["updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_service_team_members_variants"), "service_team_members", ["variants"], unique=False
    )
    op.add_column(
        "service_composition_variants", sa.Column("member_id", sa.BIGINT(), nullable=True)
    )
    op.add_column("service_composition_variants", sa.Column("team_id", sa.BIGINT(), nullable=True))
    op.drop_constraint(
        "service_composition_variants_author_id_fkey",
        "service_composition_variants",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "service_composition_variants",
        "service_teams",
        ["team_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "service_composition_variants",
        "service_team_members",
        ["member_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("service_composition_variants", "author_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_composition_variants",
        sa.Column("author_id", sa.BIGINT(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "service_composition_variants", type_="foreignkey")
    op.drop_constraint(None, "service_composition_variants", type_="foreignkey")
    op.create_foreign_key(
        "service_composition_variants_author_id_fkey",
        "service_composition_variants",
        "service_users",
        ["author_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("service_composition_variants", "team_id")
    op.drop_column("service_composition_variants", "member_id")
    op.drop_index(op.f("ix_service_team_members_variants"), table_name="service_team_members")
    op.drop_index(op.f("ix_service_team_members_updated_at"), table_name="service_team_members")
    op.drop_index(op.f("ix_service_team_members_id"), table_name="service_team_members")
    op.drop_index(op.f("ix_service_team_members_created_at"), table_name="service_team_members")
    op.drop_table("service_team_members")
    op.drop_index(op.f("ix_service_teams_variants"), table_name="service_teams")
    op.drop_index(op.f("ix_service_teams_updated_at"), table_name="service_teams")
    op.drop_index(op.f("ix_service_teams_rating"), table_name="service_teams")
    op.drop_index(op.f("ix_service_teams_rated_by"), table_name="service_teams")
    op.drop_index(op.f("ix_service_teams_name"), table_name="service_teams")
    op.drop_index(op.f("ix_service_teams_members"), table_name="service_teams")
    op.drop_index(op.f("ix_service_teams_id"), table_name="service_teams")
    op.drop_index(op.f("ix_service_teams_description"), table_name="service_teams")
    op.drop_index(op.f("ix_service_teams_created_at"), table_name="service_teams")
    op.drop_table("service_teams")
    # ### end Alembic commands ###
