"""Link volumes, chapters and pages to teams

Revision ID: 688ae9269f09
Revises: 3e0588bb3768
Create Date: 2024-12-11 15:28:37.235243

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "688ae9269f09"
down_revision: Union[str, None] = "3e0588bb3768"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("service_chapters", sa.Column("member_id", sa.BIGINT(), nullable=True))
    op.add_column("service_chapters", sa.Column("team_id", sa.BIGINT(), nullable=True))
    op.create_foreign_key(
        None, "service_chapters", "service_team_members", ["member_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "service_chapters", "service_teams", ["team_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column("service_pages", sa.Column("member_id", sa.BIGINT(), nullable=True))
    op.add_column("service_pages", sa.Column("team_id", sa.BIGINT(), nullable=True))
    op.create_foreign_key(
        None, "service_pages", "service_teams", ["team_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "service_pages", "service_team_members", ["member_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        "service_team_members_user_id_fkey", "service_team_members", type_="foreignkey"
    )
    op.drop_constraint(
        "service_team_members_team_id_fkey", "service_team_members", type_="foreignkey"
    )
    op.drop_constraint(
        "service_team_members_role_id_fkey", "service_team_members", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "service_team_members", "service_users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "service_team_members", "service_teams", ["team_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "service_team_members", "service_roles", ["role_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column("service_volumes", sa.Column("member_id", sa.BIGINT(), nullable=True))
    op.add_column("service_volumes", sa.Column("team_id", sa.BIGINT(), nullable=True))
    op.create_foreign_key(
        None, "service_volumes", "service_teams", ["team_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "service_volumes", "service_team_members", ["member_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "service_volumes", type_="foreignkey")
    op.drop_constraint(None, "service_volumes", type_="foreignkey")
    op.drop_column("service_volumes", "team_id")
    op.drop_column("service_volumes", "member_id")
    op.drop_constraint(None, "service_team_members", type_="foreignkey")
    op.drop_constraint(None, "service_team_members", type_="foreignkey")
    op.drop_constraint(None, "service_team_members", type_="foreignkey")
    op.create_foreign_key(
        "service_team_members_role_id_fkey",
        "service_team_members",
        "service_roles",
        ["role_id"],
        ["id"],
    )
    op.create_foreign_key(
        "service_team_members_team_id_fkey",
        "service_team_members",
        "service_teams",
        ["team_id"],
        ["id"],
    )
    op.create_foreign_key(
        "service_team_members_user_id_fkey",
        "service_team_members",
        "service_users",
        ["user_id"],
        ["id"],
    )
    op.drop_constraint(None, "service_pages", type_="foreignkey")
    op.drop_constraint(None, "service_pages", type_="foreignkey")
    op.drop_column("service_pages", "team_id")
    op.drop_column("service_pages", "member_id")
    op.drop_constraint(None, "service_chapters", type_="foreignkey")
    op.drop_constraint(None, "service_chapters", type_="foreignkey")
    op.drop_column("service_chapters", "team_id")
    op.drop_column("service_chapters", "member_id")
    # ### end Alembic commands ###
