"""service_pages.text set nullable to True

Revision ID: aae356a1470e
Revises: e0a1b01bb7ba
Create Date: 2024-11-18 23:47:08.689641

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aae356a1470e"
down_revision: Union[str, None] = "e0a1b01bb7ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("service_pages", "text", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    # This may break downgrading process, so let's ignore resetting changes
    op.alter_column('service_pages', 'text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    """
