"""email nullable for oauth from services without email

Revision ID: 6d3c32b28511
Revises: 0a72ddc6e89f
Create Date: 2024-11-25 18:37:04.262985

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6d3c32b28511"
down_revision: Union[str, None] = "0a72ddc6e89f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("service_users", "email", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("service_users", "email", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
