SECOND = 1
MINUTE = 60 * SECOND
HOUR = 60 * MINUTE

BYTE = 1
KILOBYTE = 1024 * BYTE
MEGABYTE = 1024 * KILOBYTE
GIGABYTE = 1024 * MEGABYTE

# Service constants
TOKEN_TTL = 6 * HOUR
TOKEN_PROLONG_INTERVAL = 5 * HOUR + 55 * MINUTE
DEFAULT_PAGE_SIZE = 15

# User's avatar related constants
MAX_AVATAR_SIZE = 10 * MEGABYTE
MAX_AVATAR_WIDTH = 1024
MAX_AVATAR_HEIGHT = 1024

USER_ONLINE_TTL = 5 * MINUTE
