SECOND = 1
MINUTE = 60 * SECOND
HOUR = 60 * MINUTE

BYTE = 1
KILOBYTE = 1024 * BYTE
MEGABYTE = 1024 * KILOBYTE
GIGABYTE = 1024 * MEGABYTE

# Service constants
TOKEN_TTL = 6 * HOUR
TOKEN_PROLONG_INTERVAL = 5 * HOUR + 55 * MINUTE
DEFAULT_PAGE_SIZE = 15

PAGE_MAX_SIZE = 20 * MEGABYTE
PAGE_ALLOWED_MIMES = ("image/png", "image/jpeg", "image/webp")

# Page types
PAGE_TEXT = "text"
PAGE_IMAGE = "image"

# User's avatar related constants
AVATAR_MAX_SIZE = 10 * MEGABYTE
AVATAR_ALLOWED_MIMES = ("image/png", "image/jpeg", "image/webp")
AVATAR_MAX_WIDTH = 1024
AVATAR_MAX_HEIGHT = 1024

USER_ONLINE_TTL = 5 * MINUTE
USER_NICKNAME_MIN = 5 # Characters


# Composition styles
STYLE_COMPOSITION_MANGA = "manga"
STYLE_COMPOSITION_MANHWA = "manhwa"
STYLE_COMPOSITION_MANHUA = "manhua"
STYLE_COMPOSITION_RANOBE = "ranobe"


COMPOSITION_STYLE_TO_PAGE_TYPE = {
    STYLE_COMPOSITION_MANGA: PAGE_IMAGE,
    STYLE_COMPOSITION_MANHWA: PAGE_IMAGE,
    STYLE_COMPOSITION_MANHUA: PAGE_IMAGE,
    STYLE_COMPOSITION_RANOBE: PAGE_TEXT,
}


# Composition statuses
STATUS_COMPOSITION_PENDING = "pending"
STATUS_COMPOSITION_COMPLETED = "completed"

# Composition variant statuses
STATUS_COMPOSITION_VARIANT_PENDING = "pending"
STATUS_COMPOSITION_VARIANT_ABANDONED = "abandoned"
STATUS_COMPOSITION_VARIANT_COMPLETED = "completed"
